version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/actions-runner/_work/mulan-assignment/mulan-assignment/dist/mulan-assignment/browser/:/usr/share/nginx/html/
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.http.routers.nginx.rule=Host(`tigasatutiga.com`)'
      - 'traefik.http.routers.nginx.entrypoints=https'
      - 'traefik.http.routers.nginx.tls=true'
      - "traefik.http.routers.nginx.tls.certresolver=porkbun"
    environment:
      - TZ=Asia/Kuala_Lumpur
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  proxy:
    external: true