# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  # push:
  #   branches: ["main"]
  release:
    types: [published]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Change to back end directory
      run: cd backend
    # - name: Install dependencies backend
    #   run: npm install
    # - name: Restart PM2 on server.js file
    #   run: pm2 restart 0
    - name: Check dir
      run: pwd
    - name: Change back to project directory
      run: cd ..
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: ng build
    - name: Stop nginx container
      run: docker rm nginx --force
    - name: Change to nginx directory
      run: cd /home/ubuntu/nginx
    - name: Check dir
      run: pwd
    - name: Start nginx container
      run: docker compose up -d

